### ISSUE TITLE
[Feature Request] Add Multiple LoRAs

### ISSUE THREAD

**Issue by syddharth** [Extraltodeus/LoadLoraWithTags#6]
As the title suggest, the ability to add multiple loras, like a LoRA stacker.

**Comment by ewebgh33** [comment]
Can chain nodes but this would be cool
This lora info node is better than others I've seen

**Comment by Extraltodeus** [comment]
Hello!

Sorry for answering a billion years later. I do not even know what a lora stacker is. I'm closing the ticket because I also do not intend to update this node any further.
